language: rust
script: make travis
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - kcov

deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: 'target/release/request_log_analyzer'
  skip_cleanup: true
  on:
    tags: true
    rust: stable
    all_branches: true
