[package]
name = "request_log_analyzer"
version = "1.4.0"
authors = ["pixelistik"]
repository = "https://github.com/pixelistik/request_log_analyzer"
license = "MIT"

[dependencies]
chrono = "0.2"
streaming-stats = "0.1"
clap = "2.12"
log = "*"
env_logger = "*"

[profile.release]
# https://lifthrasiir.github.io/rustlog/why-is-a-rust-executable-large.html
lto = true
